import { useState, useEffect } from "react";
import Head from "next/head";
import Dlayout from "../components/layouts/Dlayout";

import { GrFormAdd, GrFormClose } from "react-icons/gr";
import { BsFilterRight } from "react-icons/bs";
import { VscEdit } from "react-icons/vsc";
import { AiOutlineDelete } from "react-icons/ai";

import { database } from "../firebaseConfig";
import {
  doc,
  addDoc,
  getDoc,
  getDocs,
  collection,
  updateDoc,
  deleteDoc
} from "firebase/firestore";

import { useDispatch, useSelector } from "react-redux";
import { fetchUsers } from "../redux/features/userData/userSlice";

import { useSession, getProviders, getSession } from "next-auth/react";
import Login from "../components/Login";

export default function Home({ providers }) {
  const { data: session } = useSession();

  const dbUsers = collection(database, "userData");

  const user = useSelector((state) => state.user);
  const dispatch = useDispatch();

  const [showModal, setShowModal] = useState(false);
  const [showEditModal, setEditShowModal] = useState(false);

  const [userName, setUsername] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [email, setEmail] = useState("");
  const [company, setCompany] = useState("");

  const [singleUser, setSingleUser] = useState({});

  const [newUserName, setNewUserName] = useState('');
  const [newPhoneNumber, setNewPhoneNumber] = useState('');
  const [newEmail, setNewEmail] = useState('');
  const [newCompany, setNewCompany] = useState('');

  const getSingleId = async (id) => {
    if (id) {
      const singleData = doc(database, "userData", id);
      const data = await getDoc(singleData);

      setSingleUser({ ...data.data(), id: data.id });
    }
    setEditShowModal(true)
    setNewUserName(singleUser.userName);
    setNewPhoneNumber(singleUser.phoneNumber);
    setNewEmail(singleUser.email);
    setNewCompany(singleUser.company);
  };

  const updateUserDetail = (id) => {
    setEditShowModal(false);
    const collectionById = doc(database, "userData", id);
    updateDoc(collectionById, {
      userName: newUserName,
      phoneNumber: newPhoneNumber,
      email: newEmail,
      company: newCompany,
    })
    .then(() => {
      window.location.reload()
  })
  };

  const deleteUser = (id) => {
    const collectionById = doc(database, "userData", id);

    deleteDoc(collectionById)
    .then(() => {
        window.location.reload()
    })
  }

  useEffect(() => {
    dispatch(fetchUsers());
  }, []);

  const saveFormData = (e) => {
    e.preventDefault();
    addDoc(dbUsers, {
      userName: userName,
      phoneNumber: phoneNumber,
      email: email,
      company: company,
    }).then(() => {
      setUsername("");
      setPhoneNumber("");
      setEmail("");
      setCompany("");
    })
    .then(() => {
      window.location.reload()
  })
    setShowModal(false);
  };

  if (!session) return <Login providers={providers} />;

  return (
    <div>
      <Head>
        <title>Celetel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-6 mx-4 p-4">
        <h1 className="font-semibold text-4xl w-full">Customer Details</h1>
      </div>
      <div className="my-2 mx-4 p-4 max-w-5xl">
        <div className="flex justify-between items-center">
          <h2 className="text-xl font-semibold">The terms you are tracking</h2>
          <div className="flex justify-around items-center space-x-2 sm:space-x-4">
            <button className="text-md text-gray-500 px-5 border-2 border-gray-400 rounded-lg">
              <BsFilterRight className="inline text-gray-500" /> Filter
            </button>
            <button
              type="button"
              onClick={() => setShowModal(true)}
              className="text-md border-2 border-orange-500 px-3 md:px-5 text-white bg-orange-500 rounded-lg"
            >
              <GrFormAdd className="inline" /> Add
            </button>
            {showModal ? (
              <>
                <div className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none">
                  <div className="relative w-auto my-6 mx-auto max-w-3xl">
                    <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                      <div className="flex items-start justify-between p-5 border-b border-solid border-slate-200 rounded-t">
                        <h3 className="text-3xl font-semibold">
                          Add customer details
                        </h3>
                        <button
                          className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                          onClick={() => setShowModal(false)}
                        >
                          <GrFormClose className="bg-transparent text-black font-bold h-6 w-6 text-2xl block outline-none focus:outline-none" />
                        </button>
                      </div>
                      <div className="relative p-6 flex-auto">
                        <div className="block p-6 rounded-lg shadow-lg bg-white max-w-md">
                          <form>
                            <div className="grid grid-cols-2 gap-4">
                              <div className="form-group mb-6">
                                <input
                                  type="text"
                                  className="form-control
                                    block
                                    w-full
                                    px-3
                                    py-1.5
                                    text-base
                                    font-normal
                                    text-gray-700
                                    bg-white bg-clip-padding
                                    border border-solid border-gray-300
                                    rounded
                                    transition
                                    ease-in-out
                                    m-0
                                    focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                  aria-describedby="emailHelp123"
                                  placeholder="User name"
                                  onChange={(e) => setUsername(e.target.value)}
                                  value={userName}
                                />
                              </div>
                              <div className="form-group mb-6">
                                <input
                                  type="tel"
                                  onChange={(e) =>
                                    setPhoneNumber(e.target.value)
                                  }
                                  value={phoneNumber}
                                  className="form-control
                                    block
                                    w-full
                                    px-3
                                    py-1.5
                                    text-base
                                    font-normal
                                    text-gray-700
                                    bg-white bg-clip-padding
                                    border border-solid border-gray-300
                                    rounded
                                    transition
                                    ease-in-out
                                    m-0
                                    focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                  aria-describedby="emailHelp124"
                                  placeholder="Phone No."
                                />
                              </div>
                            </div>
                            <div className="form-group mb-6">
                              <input
                                type="email"
                                onChange={(e) => setEmail(e.target.value)}
                                value={email}
                                className="form-control block
                                  w-full
                                  px-3
                                  py-1.5
                                  text-base
                                  font-normal
                                  text-gray-700
                                  bg-white bg-clip-padding
                                  border border-solid border-gray-300
                                  rounded
                                  transition
                                  ease-in-out
                                  m-0
                                  focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                placeholder="Email address"
                              />
                            </div>
                            <div className="form-group mb-6">
                              <input
                                type="text"
                                onChange={(e) => setCompany(e.target.value)}
                                value={company}
                                className="form-control block
                                  w-full
                                  px-3
                                  py-1.5
                                  text-base
                                  font-normal
                                  text-gray-700
                                  bg-white bg-clip-padding
                                  border border-solid border-gray-300
                                  rounded
                                  transition
                                  ease-in-out
                                  m-0
                                  focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                placeholder="Company"
                              />
                            </div>
                            <button
                              className="bg-emerald-500 text-white active:bg-emerald-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                              type="submit"
                              onClick={saveFormData}
                            >
                              Save User details
                            </button>

                            <button
                              className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                              type="button"
                              onClick={() => setShowModal(false)}
                            >
                              Close
                            </button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
              </>
            ) : null}
          </div>
        </div>
        {user.loading && <div>Loading....</div>}
        {!user.loading && user.error ? <div>Error: {user.error}</div> : null}
        {!user.loading && user.users.length ? (
          <div className="overflow-x-auto relative shadow-md sm:rounded-lg my-4">
            <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                  <th scope="col" className="py-3 px-6">
                    E-mail
                  </th>
                  <th scope="col" className="py-3 px-6">
                    Username
                  </th>
                  <th scope="col" className="py-3 px-6">
                    Phone No.
                  </th>
                  <th scope="col" className="py-3 px-6">
                    Company
                  </th>
                  <th scope="col" className="py-3 px-6">
                    Action
                  </th>
                </tr>
              </thead>
              <tbody>
                {user.users.map((users) => {
                  return (
                    <tr
                      key={users.id}
                      className="bg-white border-b dark:bg-gray-900 dark:border-gray-700"
                    >
                      <th
                        scope="row"
                        className="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white"
                      >
                        {users.email}
                      </th>
                      <td className="py-4 px-6">{users.userName}</td>
                      <td className="py-4 px-6">{users.phoneNumber}</td>
                      <td className="py-4 px-6">{users.company}</td>
                      <td className="py-4 px-6">
                        <div className="space-x-2">
                          <VscEdit
                            type="button"
                            onClick={() => {
                              getSingleId(users.id);
                            }}
                            className="inline-block text-lg text-blue-500 cursor-pointer"
                          />
                          {showEditModal ? (
                            <>
                              <div className="justify-center items-center flex overflow-x-hidden overflow-y-auto fixed inset-0 z-50 outline-none focus:outline-none">
                                <div className="relative w-auto my-6 mx-auto max-w-3xl">
                                  <div className="border-0 rounded-lg shadow-lg relative flex flex-col w-full bg-white outline-none focus:outline-none">
                                    <div className="flex items-start justify-between p-5 border-b border-solid border-slate-200 rounded-t">
                                      <h3 className="text-3xl font-semibold">
                                        Edit customer detail
                                      </h3>
                                      <button
                                        className="p-1 ml-auto bg-transparent border-0 text-black opacity-5 float-right text-3xl leading-none font-semibold outline-none focus:outline-none"
                                        onClick={() => setEditShowModal(false)}
                                      >
                                        <GrFormClose className="bg-transparent text-black font-bold h-6 w-6 text-2xl block outline-none focus:outline-none" />
                                      </button>
                                    </div>
                                    <div className="relative p-6 flex-auto">
                                      <div className="block p-6 rounded-lg shadow-lg bg-white max-w-md">
                                        <form>
                                          <div className="grid grid-cols-2 gap-4">
                                            <div className="form-group mb-6">
                                              <input
                                                type="text"
                                                className="form-control
                                                                        block
                                                                        w-full
                                                                        px-3
                                                                        py-1.5
                                                                        text-base
                                                                        font-normal
                                                                        text-gray-700
                                                                        bg-white bg-clip-padding
                                                                        border border-solid border-gray-300
                                                                        rounded
                                                                        transition
                                                                        ease-in-out
                                                                        m-0
                                                                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                                aria-describedby="emailHelp123"
                                                placeholder={"userName"}
                                                onChange={(e) =>
                                                  setNewUserName(e.target.value)
                                                }
                                                value={newUserName}
                                              />
                                            </div>
                                            <div className="form-group mb-6">
                                              <input
                                                type="tel"
                                                onChange={(e) =>
                                                  setNewPhoneNumber(e.target.value)
                                                }
                                                value={newPhoneNumber}
                                                className="form-control
                                                                        block
                                                                        w-full
                                                                        px-3
                                                                        py-1.5
                                                                        text-base
                                                                        font-normal
                                                                        text-gray-700
                                                                        bg-white bg-clip-padding
                                                                        border border-solid border-gray-300
                                                                        rounded
                                                                        transition
                                                                        ease-in-out
                                                                        m-0
                                                                        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                                aria-describedby="emailHelp124"
                                                placeholder={"phoneNumber"}
                                              />
                                            </div>
                                          </div>
                                          <div className="form-group mb-6">
                                            <input
                                              type="email"
                                              onChange={(e) =>
                                                setNewEmail(e.target.value)
                                              }
                                              value={newEmail}
                                              className="form-control block
                                                                      w-full
                                                                      px-3
                                                                      py-1.5
                                                                      text-base
                                                                      font-normal
                                                                      text-gray-700
                                                                      bg-white bg-clip-padding
                                                                      border border-solid border-gray-300
                                                                      rounded
                                                                      transition
                                                                      ease-in-out
                                                                      m-0
                                                                      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                              placeholder={"email"}
                                            />
                                          </div>
                                          <div className="form-group mb-6">
                                            <input
                                              type="text"
                                              onChange={(e) =>
                                                setNewCompany(e.target.value)
                                              }
                                              value={newCompany}
                                              className="form-control block
                                                                      w-full
                                                                      px-3
                                                                      py-1.5
                                                                      text-base
                                                                      font-normal
                                                                      text-gray-700
                                                                      bg-white bg-clip-padding
                                                                      border border-solid border-gray-300
                                                                      rounded
                                                                      transition
                                                                      ease-in-out
                                                                      m-0
                                                                      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                              placeholder={"company"}
                                            />
                                          </div>
                                          <button
                                            className="bg-emerald-500 text-white active:bg-emerald-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                                            type="button"
                                            onClick={() => {updateUserDetail(singleUser.id)}}
                                          >
                                            Edit this user details
                                          </button>

                                          <button
                                            className="text-red-500 background-transparent font-bold uppercase px-6 py-2 text-sm outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
                                            type="button"
                                            onClick={() =>
                                              setEditShowModal(false)
                                            }
                                          >
                                            Close
                                          </button>
                                        </form>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="opacity-25 fixed inset-0 z-40 bg-black"></div>
                            </>
                          ) : null}
                          <AiOutlineDelete type="button"
                          onClick={() => deleteUser(users.id)}
                          className="inline-block text-lg cursor-pointer" />
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        ) : null}
      </div>
    </div>
  );
}

Home.Layout = Dlayout;

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}
